import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import styles from "../styles/Home.module.css";
import { Box, Container, Grid, Typography } from "@mui/material";
import ImageBox from "../components/Image";
import CallToActionBlock from "../components/CallToActionBlock";

export default function Home() {
  return (
    <>
      <Head>
        <title>Outliant React Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Container
        maxWidth="lg"
        disableGutters
        className={styles["home-content"]}
      >
        <Grid container spacing={4} alignItems="stretch">
          <Grid item xs={3}>
            <Typography variant="h4" component="h2" mb={2}>
              Header Text
            </Typography>
            <Typography
              variant="body2"
              component="p"
              color="secondary"
              sx={{ fontSize: "16px" }}
            >
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
              iusto nobis asperiores, aspernatur iste deserunt est veritatis
              temporibus voluptatem consequatur iure non perferendis, veniam
              dolorem. Quas ipsa laboriosam neque maiores!
            </Typography>
          </Grid>
          <Grid item xs={6}>
            <Box sx={{ padding: "0 1rem" }}>
              <ImageBox width="100%" height="500px" bg="#c4c4c4" />
            </Box>
          </Grid>
          <Grid
            item
            xs={3}
            sx={{
              display: "flex",
              flexFlow: "column wrap",
              justifyContent: "flex-end",
            }}
          >
            <Typography variant="h4" component="h2" mb={2}>
              Header Text
            </Typography>
            <Typography variant="body2" component="p" color="secondary">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
              iusto nobis asperiores, aspernatur iste deserunt est veritatis
              temporibus voluptatem consequatur iure non perferendis, veniam
              dolorem. Quas ipsa laboriosam neque maiores!
            </Typography>
          </Grid>
        </Grid>
      </Container>
      <CallToActionBlock />
    </>
  );
}
